version: 0.0
os: linux
files:
  - source: build/libs/spring-boot-aws-1.0-SNAPSHOT.jar
    destination: /home/ec2-user/app/step2
permissions:
  - object: /home/ec2-user/app/step2
hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/clean_service.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 60
      runas: root